### PR TITLE
Infinite Scroll for ListView and GridView

### PR DESCRIPTION
**Pull request by snehmehta**
Ticket: #772

EDL Definition
```yaml
    ListView:
      onScrollEnd:
        invokeAPI:
          name: getPeople
          onResponse: |
            //@code

            var results = getPeople.body.results;
            var oldResults = ensemble.storage.users;
            var total = oldResults.concat(results);

            ensemble.storage.users = total;

      item-template:
        data: ${ensemble.storage.users}
        name: user 

        template:
          Text:
            text: ${user.name.first}

```

### CODE REVIEW

**Comment by sharjeelyunus** [comment]
@snehmehta 

Just a little confusion, will `onScrollEnd` work at the bottom of the screen only?
because on the messages screen, we need it at the top of the screen as well i.e. onScrollEnd (at the top of the screen), because messages are in reverse order

**Comment by vusters** [comment]
This restricts the use to storage only and there's potential for errors. Please make sure AppDevs understand these:
- items stay in storage, so when you come back to this page, make sure to re-initialize, othewise you'll just add duplicate data to it.
- how to clean up the storage when you move away from the page.

Ideally we have a proper binding between API and ListView/GridView to automatically aggregate the data, but this is useful today.

Please change the onScrollEnd to:
- onScrollToTop
- onScrollToBottom
These are generic enough to be used for other purposes, plus support the use case Sharjeel mentioned.

**Comment by kmahmood74** [comment]
Hi @snehmehta Vu had comments on your PR, could you please fix this as multiple customers are blocked on this

**Comment by snehmehta** [comment]
Updated EDL

```yaml
    ListView:
      style: {reverse: true} # This will start building the list from the bottom instead top and onScrollEnd works the same.
      onScrollEnd:
        invokeAPI:
          name: getPeople
          onResponse: |
            //@code

            var results = getPeople.body.results;
            var oldResults = ensemble.storage.users;
            var total = oldResults.concat(results);

            ensemble.storage.users = total;

      item-template:
        data: ${ensemble.storage.users}
        name: user 

        template:
          Text:
            text: ${user.name.first}

```

**Pull request merged**
