### PR TITLE
WIP: Added support for inputs to be defined explicitly

### PR DESCRIPTION
**Pull request by hemish11**
Closes https://github.com/EnsembleUI/ensemble/issues/356

### CODE REVIEW

**Comment by kmahmood74** [comment]
regarding allowing inputs - @hemish11 @vusters @snehmehta  I think we must have an "optional default value" for each input. As we create re-usable widgets and templates, they simply won't work without the default values and default values should not be in the code with checks for null but should be explicitly defined in the input section. 

this will allow people to view the template and then configure it.

**Comment by hemish11** [comment]
Also, it would be good to define whether an input is required or not, and if it is required, then it can throw an error if that parameter is not provided.

**Comment by kmahmood74** [comment]
> Also, it would be good to define whether an input is required or not, and if it is required, then it can throw an error if that parameter is not provided.

I agree. 
Please come up with the YAML proposal for this.

**Comment by hemish11** [comment]
We can do something like:
```yaml
View:
  input:
    - parameter: # Not sure about the name parameter, maybe can change it to something else
        name: first_name # The name of the parameter
        isRequired: true # Defaults to false
    - parameter:
        name: last_name
    - parameter:
        name: words[] # Maybe we can add [] to define it as an array
```

What should be the exact word instead of the parameter? Also wanted suggestions on adding [] in the postfix of a name to make it an array and thereby allow some preliminary validations or so.

**Comment by kmahmood74** [comment]
suggest the following variation on what you proposed. I think we should define the type as well even if we don't enforce it for now. There are just a few types - string, number, object (could be js or json), array, date, boolean, any

any -> its the default. Allows us to be backward compatible. Also useful in places where the screen accepts different types for the same input. For example, can accept names as a string if there is one or as an array if more than one. 

```yaml
View:
  inputs:
    - input: 
        name: first_name # The name of the parameter
        isRequired: true # Defaults to false
        default: John
    - input:
        name: last_name
       default: Doe
       type: string
    - input:
        name: words
        type: array
        default: ['hello']
```
@vusters @snehmehta what do you think? I think we should just do this properly instead of having to go back another dozen times adding things we know we will need for sure

**Comment by vusters** [comment]
Make it backward compatible:
```
View:
  inputs:
     # short-hand for just name only. This is how it works today
     - occupation
     
     # more details
     - name: age
        type: integer
        default: 20
```
This can be the same for API/Custom Widget's inputs.

**Comment by kmahmood74** [comment]
this PR only defines inputs as array in the schema? @hemish11 is it still being developed?

**Comment by hemish11** [comment]
Yes @kmahmood74, It's still under development

**Comment by kmahmood74** [comment]
@hemish11 so we are not doing this? this was closed without any merge?

**Pull request closed without merging**
