### PR TITLE
Add getInitialMessage method for handling push notification in Terminated App State

### PR DESCRIPTION
**Pull request by vinothvino42**
Ticket: #1027

### CODE REVIEW

**Review by vusters — CHANGES_REQUESTED** [review]
are you missing some files? You are removing the logic to execute callbacks but added somewhere else?

**Comment by vusters** [comment]
Here's how you can resolve the race condition:
- in NotificationManager, have init() returns the initial message.
- in main, await for the NotificationManager's init() and retreieve this initial message.
- if the messge has screenId/screenName, pass them into EnsembleApp.

This will ensure the 1st scren you load will be the screenId/screenName you have.

**Comment by vinothvino42** [comment]
> are you missing some files? You are removing the logic to execute callbacks but added somewhere else?

I added it in the screen widget, it's because the ensemble_app fetches the definition and then only it renders the widget. So I just added it in the screen widget, here the material app is already initialized with the definition.

**Comment by vinothvino42** [comment]
@vusters I'll merge this PR

**Pull request merged**
