### PR TITLE
Markdown https://github.com/EnsembleUI/ensemble/issues/262

### PR DESCRIPTION
**Pull request by Moeez1999**

### CODE REVIEW

**Comment by Moeez1999** [comment]
I created a seprate branch but didnt get how previous commit is involved in it

**Review by vusters — APPROVED** [review]

**Comment by vusters** [comment]
Looks good. Please isolate the markdown code then we can merge.

**Comment by Moeez1999** [comment]
I didnt get it sorry

**Comment by vusters** [comment]
You can merge the Markdown code - it looks good. But please don't have anything Gradient-related in there.

**Comment by vusters** [comment]
Please remove this PR as you have the other one.

**Comment by vusters** [comment]
Please resolve conflict and merge.

**Comment by kmahmood74** [comment]
@Moeez1999 your PR has been approved, can you please resolve conflicts and merge please.

**Pull request closed without merging**
