### PR TITLE
Handle flutter & unhandled platform errors

### PR DESCRIPTION
**Pull request by vinothvino42**
In this PR, I handled flutter-related errors and displayed the error widget

### CODE REVIEW

**Review by vusters — COMMENTED** [review]
we are catching the errors on main() of both ensemble_starter and ensemble_live. You want to remove from there?

**Comment by vinothvino42** [comment]
> we are catching the errors on main() of both ensemble_starter and ensemble_live. You want to remove from there?

Yes, Can you check the new changes?

**Review by vusters — APPROVED** [review]

**Comment by kmahmood74** [comment]
@vinothvino42 this was approved in July. what's the status here?

**Comment by kmahmood74** [comment]
@vinothvino42 what's the delay here!!!

**Comment by vinothvino42** [comment]
Sanjay handled a few flutter exceptions for the studio to be hanged (ex: incorrect parent widget exception). Right now, this change will trigger the overlay view whenever a minor error occurs in the app, so we need to do it with a different approach. Having a backup of this change and closing it as of now for monorepo

**Pull request closed without merging**
