### PR TITLE
Add onChange to DateRange widget

### PR DESCRIPTION
**Pull request by vinothvino42**
Ticket: #779 

Added the following
1. Schema for the DateRange widget
2. onChange event updated

### CODE REVIEW

**Comment by vusters** [comment]
@vinothvino42 this widget was developed for demo and has not been fully implemented (hence the lack of schema). Please got hrough the entire class and make sure all features are working, and also add the schema.

**Comment by vinothvino42** [comment]
> @vinothvino42 this widget was developed for demo and has not been fully implemented (hence the lack of schema). Please got hrough the entire class and make sure all features are working, and also add the schema.

I checked it and it is working fine. Today I added `schema` for the `DateRange` widget and `suffixIcon` property

**Review by vusters — CHANGES_REQUESTED** [review]
@vinothvino42 again this schema won't work - as I have mentioned several times. Please see how the rest of the widgets on how to write the right schema

**Review by vinothvino42 — COMMENTED** [review]
I updated it. Can you check again? @vusters

**Review by vusters — APPROVED** [review]

**Pull request merged**
