### PR TITLE
https://github.com/EnsembleUI/ensemble/issues/1128 submit/validate me…

### PR DESCRIPTION
**Pull request by kmahmood74**
…thods on Form so they could be called from anywhere and for multiple forms

### CODE REVIEW

**Comment by kmahmood74** [comment]
also fixes #641

**Comment by kmahmood74** [comment]
lint is failing due to files that are not even in this PR!!! Fixing it.

**Comment by kmahmood74** [comment]
@vusters the only change is in form.dart rest of the files are there to fix the lint issues. It would not take you more than 5 mins to review this. please do it quickly

**Review by vusters — APPROVED** [review]
Very nice !

**Pull request merged**
