### PR TITLE
TextInput/PasswordInput: maxLength and maxLengthEnforcement 

### PR DESCRIPTION
**Pull request by sharjeelyunus**
Closes: https://github.com/EnsembleUI/ensemble/issues/1548

EDL:

```yaml
 - TextInput:
       label: Hello world
       maxLength: 10
       maxLengthEnforcement: none # none, enforced, truncateAfterCompositionEnds
- PasswordInput:
       maxLength: 8
       maxLengthEnforcement: enforced
```

image

### CODE REVIEW

**Comment by amin-nas** [comment]
@sharjeelyunus  Is there another state beside `none` and `enforced`?
Boolean seems more inline with how we do these properties:
```yaml
maxLengthEnforced: true # default to false
```

Please link the relevant ticket. That's where we should discuss the EDL ahead of implementation.

**Comment by kmahmood74** [comment]
> @sharjeelyunus Is there another state beside `none` and `enforced`? Boolean seems more inline with how we do these properties:
> 
> ```yaml
> maxLengthEnforced: true # default to false
> ```
> 
> Please link the relevant ticket. That's where we should discuss the EDL ahead of implementation.

there is - truncateAfterCompositionEnds it's there in the code as well. 

  /// Users can still input text if the current value is composing even after
  /// reaching the max length limit. After composing ends, the value will be
  /// truncated.

**Comment by kmahmood74** [comment]
every PR must reference its ticket and must put the yaml in the ticket as well. @sharjeelyunus please provide that

**Review by kmahmood74 — APPROVED** [review]
I am assuming maxLengthEnforcement is optional and the default behavior is 'enforced' when maxLength is specified and maxLengthEnforcement is not.

**Comment by sharjeelyunus** [comment]
> I am assuming maxLengthEnforcement is optional and the default behavior is 'enforced' when maxLength is specified and maxLengthEnforcement is not.

hey, the default is none, let me know if you want me to make it enforced by default

**Comment by kmahmood74** [comment]
> > I am assuming maxLengthEnforcement is optional and the default behavior is 'enforced' when maxLength is specified and maxLengthEnforcement is not.
> 
> hey, the default is none, let me know if you want me to make it enforced by default

default is not none in flutter, it is enforced. We should keep the same default. 

from flutter - 

  /// Determines how the [maxLength] limit should be enforced.
  ///
  /// Defaults to [MaxLengthEnforcement.enforced].
  ///
  /// {@macro flutter.services.textFormatter.maxLengthEnforcement}
  final MaxLengthEnforcement? maxLengthEnforcement;

**Pull request merged**
