### PR TITLE
Support for expressions in header and footer

### PR DESCRIPTION
**Pull request by hemish11**
Fixes https://github.com/EnsembleUI/ensemble/issues/847 and https://github.com/EnsembleUI/ensemble/issues/763

### CODE REVIEW

**Review by snehmehta — COMMENTED** [review]
The ticket expects to eval pagestyle as well, have you check it's evaluating or not?

[PageModel - pageStyles](https://github.com/hemish11/ensemble/blob/d66bbf6ff47dc98f51fe3c31ff29a47b57ce5f5f/lib/page_model.dart#L136-L137)

**Comment by hemish11** [comment]
@snehmehta Yes, it does evaluate the page style.

**Review by vusters — APPROVED** [review]
Sufficient to unblock folks for now. The proper solution is not to add eval() everywhere but to convert the page into a widget so evaluation and bindings is automatic (just like a normal widget)

**Comment by kmahmood74** [comment]
@hemish11 this is not right. You missed the styles under View even though both #763 and #847 mentioned View specifically. I see this code - 

```
    LinearGradient? backgroundGradient = Utils.getBackgroundGradient(
        widget._pageModel.pageStyles?['backgroundGradient']);
    Color? backgroundColor =
        Utils.getColor(widget._pageModel.pageStyles?['backgroundColor']);
        ```
in Page.dart so it is clear that backgroundColor or gradient are not being evaluated. 

Please don't just pick and choose and do this for ALL STYLES on View.

**Pull request merged**
