### PR TITLE
Added support for audioplayer

### PR DESCRIPTION
**Pull request by hemish11**
Closes https://github.com/EnsembleUI/ensemble/issues/1303

Adds the following new actions for the audio player:
- **playAudio**: Plays the given audio
  - **source**: Takes either assets or URLs for the audio source
  - **volume**: Controls the volume, which can be between 0 and 1
  - **balance**: Controls the balance between the left and right speaker, can be between -1 and 1
  - **position**: Sets the initial position from which to play the audio from, and takes value in second
- **pauseAudio**: Pauses the currently playing audio
- **resumeAudio**: Resumes the previously stopped audio
- **seekAudio**: Moves the audio to a given time
  - **position**: Sets the position, takes value in second

Example EDL:
```yaml

View:
  header:
    title: Audio Player
  styles:
    scrollableView: true

  body:
    Column:
      styles:
        gap: 16
        padding: 24
      children:
        - Button:
            label: Play Audio
            onTap:
              playAudio:
                source: "https://file-examples.com/storage/fecea16b5a65ec8d9978112/2017/11/file_example_MP3_700KB.mp3"
                volume: 1 # 0 to 1
                balance: 0 # -1 to 1
                position: 2 # in seconds
                onComplete:
                  executeCode:
                    body: |
                      console.log("Audio Played");

        - Button:
            label: Pause Audio
            onTap:
              pauseAudio:

        - Button:
            label: Stop Audio
            onTap:
              stopAudio:

        - Button:
            label: Resume Audio
            onTap:
              resumeAudio:

        - Button:
            label: Seek Audio at 4 second
            onTap:
              seekAudio:
                position: 2

```

### CODE REVIEW

**Comment by hemish11** [comment]
Schema PR: https://github.com/EnsembleUI/ensemble-web-studio/pull/820

**Comment by hemish11** [comment]
The changes in these files are done in order to resolve the lint issues:
- `lib/ensemble_app.dart`
- `lib/framework/bindings.dart`
- `lib/framework/config.dart`
- `lib/framework/scope.dart`
- `lib/framework/theme_manager.dart`
- `lib/framework/view/page.dart`
- `lib/framework/widget/widget.dart`
- `lib/layout/box/base_box_layout.dart`
- `lib/page_model.dart`
- `lib/widget/helpers/controllers.dart`

**Comment by kmahmood74** [comment]
EDL should always be on the ticket itself and not on the PR.

**Comment by kmahmood74** [comment]
@hemish11 can you please make the changes that @vusters suggested in the standup - look at how startTimer/stopTimer works and use a similar mechanism to allow id for your action. We don't need the audio widget.

**Review by kmahmood74 — APPROVED** [review]

**Pull request merged**
